name       : haskell-data-accessor-template
version    : 0.2.1.16
release    : 1
source     :
    - https://hackage.haskell.org/package/data-accessor-template-0.2.1.16/data-accessor-template-0.2.1.16.tar.gz : 93e7f2120b8974d81a4acc56bd6a5b7121dac4672d974a42512c169c6937ed95
license    : BSD-3-Clause
component  : programming.haskell
summary    : Utilities for accessing and manipulating fields of records
description: |
    Utilities for accessing and manipulating fields of records
builddeps  :
    - haskell-cabal-install
    - haskell-data-accessor-devel
    - haskell-utility-ht-devel
rundeps    :
    - devel:
        - haskell-data-accessor-devel
        - haskell-utility-ht-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
